[package]
name = "rust_toy_parser"
version = "0.1.0"
authors = ["daikimiura <daikiii5555@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
